import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import Head from "next/head";
import { map } from "@trpc/server/observable";

import { useEffect, useState } from "react";


export default function Home() {
    // const [postData, setPostData] = useState<Array<{
    //   id: string;
    //   createdAt: Date;
    //   content: string;
    //   authorId: string;
    // }>>([]); // Updated the initial state type
    const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            WELCOME TO <span className="text-[hsl(280,100%,70%)]">RIZZTER</span>
          </h1>
        </div>

        <div>
          {!user.isSignedIn && <SignInButton></SignInButton>}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        {/* <div className="flex flex-col items-center gap-2 text-white">
          
          {postData.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div> */}
      </main>
    </>
  );
}
